name: weather_app
description: "Weather application using open-meteo.com API"
publish_to: 'none'

version: 0.9.2

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: any
  fl_chart: ^0.67.0
  location: ^5.0.0
  intl: ^0.19.0
  shared_preferences: any
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true